Adds available RL library configs on error message if entry point is invalid (#2713)
# Description

This PR show the available RL library (and algorithms) configs on error
message when an entry point key is not available for a given task.

Example: for `./isaaclab.sh -p
scripts/reinforcement_learning/sb3/train.py
--task=Isaac-Cart-Double-Pendulum-Direct-v0 --headless`

Before:

```
ValueError: Could not find configuration for the environment: 'Isaac-Cart-Double-Pendulum-Direct-v0'. Please check that the gym registry has the entry point: 'sb3_cfg_entry_point'.
```

After

```
ValueError: Could not find configuration for the environment: 'Isaac-Cart-Double-Pendulum-Direct-v0'.
Please check that the gym registry has the entry point: 'sb3_cfg_entry_point'.
Existing RL library (and algorithms) config entry points: 
  |-- rl_games: PPO
  |-- skrl: PPO, IPPO, MAPPO
```

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with
`./isaaclab.sh --format`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [x] I have updated the changelog and the corresponding version in the
extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already
exists there

<!--
As you go through the checklist above, you can mark something as done by
putting an x character in it

For example,
- [x] I have done this task
- [ ] I have not done this task
-->